name: Auto Release Checklist

on:
  pull_request:
    branches: [main]
    types: [opened, reopened]

permissions:
  pull-requests: write

jobs:
  append_checklist:
    if: |
      startsWith(github.head_ref, 'feature_') ||
      startsWith(github.head_ref, 'story_') ||
      startsWith(github.head_ref, 'release_')
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Get current PR body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        id: get_pr_body
        run: |
          echo "📝 Fetching existing PR body..."
          echo "ℹ️ Repo: $REPO"
          echo "ℹ️ PR Number: $PR_NUMBER"
          RESPONSE=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            https://api.github.com/repos/$REPO/pulls/$PR_NUMBER)
          BODY=$(echo "$RESPONSE" | jq -r '.body // ""')
          echo "ℹ️ Current PR body:"
          echo "$BODY"
          echo "body<<EOF" >> $GITHUB_OUTPUT
          echo "$BODY" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT
          echo "✅ PR body fetched and stored."

      - name: Append checklist to PR body
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          REPO: ${{ github.repository }}
          PR_NUMBER: ${{ github.event.pull_request.number }}
        run: |
          echo "📝 Reading checklist from .github/release-checklist.md..."
          CHECKLIST=$(cat .github/pr-checklist.md)
          echo "✅ Checklist file successfully read."
          echo "📝 Appending checklist to PR body..."
          echo "ℹ️ Repo: $REPO"
          echo "ℹ️ PR Number: $PR_NUMBER"
          EXISTING_BODY="${{ steps.get_pr_body.outputs.body }}"
          if echo "$EXISTING_BODY" | grep -qF -- "<!-- PR_CHECKLIST_MARKER -->"; then
            echo "✅ Checklist already present. Skipping update."
            exit 0
          fi
          echo "ℹ️ Checklist to append:"
          echo "$CHECKLIST"
          echo "ℹ️ Existing PR body:"
          echo "$EXISTING_BODY"
          NEW_BODY="${EXISTING_BODY}

          ${CHECKLIST}"
          NEW_BODY_ESCAPED=$(jq -n --arg body "$NEW_BODY" '{body: $body}')
          curl -s -X PATCH -H "Authorization: token $GITHUB_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$NEW_BODY_ESCAPED" \
            https://api.github.com/repos/$REPO/pulls/$PR_NUMBER
          echo "✅ PR body updated successfully."
